<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CryptoHelper" Version="5.1.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.22.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebChat.Connection\WebChat.Connection.csproj" />
    <ProjectReference Include="..\WebChat.Data\WebChat.Models.csproj" />
    <ProjectReference Include="..\WebChat.Hub\WebChat.Hubs.csproj" />
  </ItemGroup>

</Project>
